apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "56Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: password
          mountPath: /secrets
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: password
        secret:
          secretName: secret
      - name: config-volume
        configMap:
          name: configmap
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
