apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config  
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: my-configmap
